# Welcome to Serverless!
#
# This file is the main config file for this lambda service.
#
# For full config options, check the docs:
#    docs.serverless.com
#

service: takeon-validation-wrangler # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-west-2
  stage: dev
  deploymentBucket: takeon.validation.deployment

package:
 exclude:
   - ./**
   - venv/**
   - .vscode/**
   - .cache/**
   - test/**
   - Docs/**
 include:
   - ./bin/**

functions:
  main:
    handler: bin/main
    role: ${file(./serverless.config.json):ROLE}
    environment:
      INPUT_QUEUE_URL: ${file(./serverless.config.json):INPUT_QUEUE_URL}
      OUTPUT_QUEUE_URL: ${file(./serverless.config.json):OUTPUT_QUEUE_URL}
    events:
      - sqs:
         arn: ${file(./serverless.config.json):INPUT_QUEUE_ARN}
         batchSize: 1
    timeout: 3
    memorySize: 512
